# Generated by Django 4.0.4 on 2022-04-26 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
